// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoAPI;

#nullable disable

namespace ToDoAPI.Migrations
{
    [DbContext(typeof(ToDoListDBContext))]
    [Migration("20230105111005_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToDoAPI.Models.CreateToDoList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Expired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ListTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ThisWeek")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ListId");

                    b.HasIndex("CreateUserId");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("ToDoAPI.Models.CreateUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AccessLevelAdm")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AccessLevelMod")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AccessLevelOne")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ToDoAPI.Models.Task", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CreateToDoListListId")
                        .HasColumnType("int");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ListId");

                    b.HasIndex("CreateToDoListListId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("ToDoAPI.Models.CreateToDoList", b =>
                {
                    b.HasOne("ToDoAPI.Models.CreateUser", null)
                        .WithMany("ToDoList")
                        .HasForeignKey("CreateUserId");
                });

            modelBuilder.Entity("ToDoAPI.Models.Task", b =>
                {
                    b.HasOne("ToDoAPI.Models.CreateToDoList", null)
                        .WithMany("Task")
                        .HasForeignKey("CreateToDoListListId");
                });

            modelBuilder.Entity("ToDoAPI.Models.CreateToDoList", b =>
                {
                    b.Navigation("Task");
                });

            modelBuilder.Entity("ToDoAPI.Models.CreateUser", b =>
                {
                    b.Navigation("ToDoList");
                });
#pragma warning restore 612, 618
        }
    }
}
